name: Data Fetcher

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '32 23 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transifex-python

    - name: Run the script
      run: python3 transifex-data-fetcher.py
      shell: bash
      env:
        TX_TOKEN: ${{ secrets.DHIS2_TX_TOKEN }}

    - name: touch the updated file
      run: ls -al data
      shell: bash
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

   
